[package]
name = "sugar-ray"
version = "0.1.0"
authors = ["r4gus <foobarc11@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
